<a href="https://colab.research.google.com/github/seokjinwoo/EconBigData/blob/main/lec2_%EC%9B%94.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 데이터 분석에 필요한 파이썬 기초

- 파이썬의 내장되어 있는 기초 함수
- 데이터 보관 형태(scalar, vector, matrix, tensor,..., arrary)
- 데이터 분석에 필요한 라이브러리(numpy, pandas)
- 데이터 시각화에 필요한 라이브러리(matplotlib)

---

## 내장 기초 함수





In [5]:
print("Hello, world!")
print("안녕, 우석진!")

print('Hello, world!')
print('Hello', 'Python!')
print('모수',11,'개의 모형을 학습한다')


Hello, world!
안녕, 우석진!
Hello, world!
Hello Python!
모수 11 개의 모형을 학습한다


- 이렇게 문자를 이어 붙이는 것을 **연결** (concantenation)

In [8]:
"Hello" + " " + "World"
print("Hello","world")

Hello world


In [11]:
print?

### 간단한 연산(계산기)

- 더하기, 빼기, 곱하기, 나누기
- 제곱, 세제곱, 분수, 제곱근,
- 삼각함수, 로그..


In [12]:
3 + 5

8

In [13]:
3*5

15

In [16]:
2**3

8

In [18]:
(1+5)/4*3

4.5

## 데이터의 형태

- scalar, vector, matrix, (tensor)
- vector와 matrix 를 어떻게 파이썬에서 담을 것이냐.

- 리스트(list), 튜플(tuple), 배열(arrary), 데이터프레임(dataframe) 등을 활용할 수 있음

---

- 리스트: [] 안에







In [22]:
x = [1,2,3,4,5]  # x <- [1,2,3,4], x < [1,2,3,4],

# 같다는 것은 "=="

# print(x)

y = [4, 8, 1]


In [24]:
x + y

[1, 2, 3, 4, 5, 4, 8, 1]

### numpy 라이브러리

- 함수나 연산을 할 때 자주 사용되는 파이썬의 패키지
- pandas 는 데이터 관리에 유용한 모듈



In [26]:
import numpy as np

In [30]:
x = [3,4,5]
y = [4,9,7]

x+y

[3, 4, 5, 4, 9, 7]

In [32]:
# 1차원 어레이
x = np.array([3,4,5])
y = np.array([4,9,7])

x+y

array([ 7, 13, 12])

In [39]:
# 2차원 어레이
x = np.array([[1,2,5],[3,4,8]])
print(x)


# 3차원 어레이: [4,5,9]
x = np.array([[1,2,5],[3,4,8], [4,5,9]])

print(x.shape)


[[1 2 5]
 [3 4 8]]
(3, 3)


In [43]:
x = np.array([1,2,3,4,5])
print("x의 합은\n",x.sum())

x의 합은
 15


In [46]:
print("x의 평균은 \n",x.mean())

x의 평균은 
 3.0


### 데이터를 다르는 패키지 pandas

- numpy와 pandas는 짝으로 다님.
- 데이터를 불러 들임




In [49]:
import pandas as pd

df = pd.read_csv('/content/auto.csv')