<a href="https://colab.research.google.com/github/seokjinwoo/EconBigData/blob/main/lec2_%ED%99%94.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 데이터 분석에 필요한 파이썬 기초

- 파이썬은 인터프리터(interpreter)
- 파이썬에서 자주 사용되는 기초 함수들을 익힌다.
- 데이터 분석에 자주 사용되는 라이브러리(numpy, pandas)
- 데이터 시각화에 자주 사용되는 라이브러리(matplotlib)

---

### 유용한 내장 기초함수





In [ ]:
print("Hello, World!")
print("Hello, 우석진")

print('Hello, World!')
print('Hello', 'Python!')
print('모수', 11, "개의 모형을 학습한다.")



Hello, World!
Hello, 우석진
Hello, World!
Hello Python!
모수 11 개의 모형을 학습한다.


- 이렇게 단어(문자나 문장)를 이어 붙이는 것을 **연결**(concantenation)

In [ ]:
"Hello" + "World!"
"Hello" + " " + "World!"
print("Hello", "World!")

Hello World!


In [ ]:
print?
# print()?

### 간단한 연산(계산기)

- 더하기, 빼기, 곱하기, 나누기
- 간단한 함수:제곱, 세제곱, 제곱근
- 로그, 지수, 삼각함수
- 미분, 적분
- 방정식도 풀어줌




In [ ]:
3 + 5

8

In [ ]:
3 - 5

-2

In [ ]:
3 * 5

15

In [ ]:
3 / 5

0.6

In [ ]:
# 승 power, 2의 3승. 2^3

2**3

8

In [ ]:
(1+5)/4*3

4.5

### 데이터의 형태

- scalar, vector, matrix (, tensor)
- vector, matrix 를 파이썬에서 어떻게 구현할 것이냐?
- 리스트(list), 튜플(tuple), 배열(array), 데이터프레임(dataframe) 등을 활용할 수 있음


---

- 리스트: [ ] 안에 담는다.



In [ ]:
x = [1,2,3,4,5 ]  # x <- [1,2,3,4,5 ],  x < [1,2,3,4,5 ]

# 같다는 것은 어떻게 표시하냐? "=="

y = [4, 8, 1]



In [ ]:
x + y

[1, 2, 3, 4, 5, 4, 8, 1]

### numpy 라이브러리

- 연산, 데이터 분석에 자주 사용되는 함수들이 포함된 파이썬 패키지
- pandas 와 같이 자주 사용됨



In [ ]:
import numpy as np


In [ ]:
x = [3,4,5]
y = [4,9,7]
# x + y

[3, 4, 5, 4, 9, 7]

In [ ]:
x = np.array([3,4,5])
y = np.array([4,9,7])

print(x + y)

[ 7 13 12]


In [ ]:
z = np.array([[3,4,5],[4,9,7]])
print(z)

[[3 4 5]
 [4 9 7]]


In [ ]:
x = np.array([1,2,3,4,5])

In [ ]:
print("x의 합은", x.sum())

x의 합은 15


In [ ]:
print("x의 평균은", x.mean())

x의 평균은 3.0


### pandas 라이브러리

- 데이터 분석에서 가장 자주 사용되는 라이브러리
- 다양한 데이터를 읽어 들이고, 관리하는데 유용함



In [ ]:
import pandas as pd


df =  pd.read_csv("/content/auto.csv") # 복사한 경로를 붙여 넣는다.
